# Generated by Django 4.1.6 on 2023-02-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stux_auth', '0003_onetimepassword_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
