# Generated by Django 4.1.7 on 2023-02-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stux_auth', '0005_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='type',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
